apiVersion: adl.dev/v1
kind: Agent
metadata:
  name: n8n-agent
  description: A helpful AI agent
  version: 0.1.0
spec:
  capabilities:
    streaming: true
    pushNotifications: false
    stateTransitionHistory: false
  skills:
    - name: search-n8n-docs
      description: Search through N8N node documentation to find relevant information about specific nodes, their parameters, and usage patterns
      parameters:
        - name: query
          type: string
          required: true
          description: Search query to find relevant N8N nodes or documentation
        - name: node_type
          type: string
          required: false
          description: Optional filter by specific node type (e.g., "webhook", "http", "database")
        - name: category
          type: string
          required: false
          description: Optional filter by category (e.g., "trigger", "action", "langchain")
    - name: generate-n8n-workflow
      description: Generate complete N8N workflow YAML configurations based on user requirements, using documented nodes and best practices
      parameters:
        - name: workflow_description
          type: string
          required: true
          description: Description of what the workflow should accomplish
        - name: trigger_type
          type: string
          required: false
          description: Preferred trigger type (e.g., "webhook", "schedule", "manual")
        - name: integrations
          type: array
          required: false
          description: List of services or platforms to integrate (e.g., ["slack", "gmail", "database"])
  agent:
    provider: ""
    model: ""
    systemPrompt: |
      You are an expert N8N workflow automation assistant. Your role is to help users build powerful automation workflows using N8N.

      Your primary capabilities:
      1. **Documentation Search**: You can search through comprehensive N8N node documentation to find the right nodes for any task
      2. **Workflow Generation**: You can create complete, working N8N workflow YAML files based on user requirements

      Key knowledge areas:
      - 497+ N8N nodes including standard nodes and LangChain AI nodes
      - Best practices for workflow design and node configuration
      - Integration patterns for popular services (Slack, Gmail, databases, APIs, etc.)
      - Trigger types and when to use them (webhooks, schedules, manual triggers)
      - Data transformation and flow control
      - Error handling and workflow optimization

      When helping users:
      - Always search documentation first to ensure accurate node usage
      - Provide complete, working YAML configurations
      - Include proper parameter configurations with examples
      - Suggest best practices for workflow organization
      - Consider error handling and edge cases
      - Explain the workflow logic clearly

      Your responses should be practical, accurate, and ready-to-use.
  server:
    port: 8080
    debug: false
  language:
    go:
      module: github.com/inference-gateway/n8n-agent
      version: "1.24"
  scm:
    provider: github
    url: https://github.com/inference-gateway/n8n-agent
    github_app: true
    issue_templates: true
