// Code generated by ADL CLI v0.23.6. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package logger

import (
	"context"

	zap "go.uber.org/zap"
	zapcore "go.uber.org/zap/zapcore"

	config "github.com/inference-gateway/n8n-agent/config"
)

// NewLogger creates a new zap.Logger instance
func NewLogger(ctx context.Context, cfg *config.Config) (*zap.Logger, error) {
	var zapConfig zap.Config

	if cfg.Environment == "development" {
		zapConfig = zap.NewDevelopmentConfig()
		zapConfig.EncoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder
	} else {
		zapConfig = zap.NewProductionConfig()
		zapConfig.EncoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder
	}

	zapConfig.EncoderConfig.TimeKey = "timestamp"
	zapConfig.EncoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder

	zapLogger, err := zapConfig.Build()
	if err != nil {
		return nil, err
	}

	return zapLogger, nil
}
