// Code generated by ADL CLI v0.18.2 on 2025-09-06. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package skills

import (
	"context"
	"fmt"
	"strings"
)

// GenerateN8nWorkflowParams represents the input parameters for the generate-n8n-workflow skill
type GenerateN8nWorkflowParams struct {
	WorkflowDescription string   `json:"workflow_description"`
	TriggerType         string   `json:"trigger_type,omitempty"`
	Integrations        []string `json:"integrations,omitempty"`
}

// GenerateN8nWorkflowTool implements the generate-n8n-workflow skill
type GenerateN8nWorkflowTool struct{}

// GetName returns the tool name
func (t *GenerateN8nWorkflowTool) GetName() string {
	return "generate-n8n-workflow"
}

// GetDescription returns the tool description
func (t *GenerateN8nWorkflowTool) GetDescription() string {
	return "Generate complete N8N workflow YAML configurations based on user requirements, using documented nodes and best practices"
}

// GetParameters returns the tool parameters schema
func (t *GenerateN8nWorkflowTool) GetParameters() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"workflow_description": map[string]any{
				"type":        "string",
				"description": "Description of what the workflow should accomplish",
			},
			"trigger_type": map[string]any{
				"type":        "string",
				"description": "Preferred trigger type (e.g., \"webhook\", \"schedule\", \"manual\")",
			},
			"integrations": map[string]any{
				"type":        "array",
				"description": "List of services or platforms to integrate (e.g., [\"slack\", \"gmail\", \"database\"])",
				"items": map[string]any{
					"type": "string",
				},
			},
		},
		"required": []string{"workflow_description"},
	}
}

// Execute generates an N8N workflow based on the requirements
func (t *GenerateN8nWorkflowTool) Execute(ctx context.Context, params map[string]any) (string, error) {
	// Parse parameters
	var p GenerateN8nWorkflowParams
	if desc, ok := params["workflow_description"].(string); ok {
		p.WorkflowDescription = strings.TrimSpace(desc)
	} else {
		return "", fmt.Errorf("workflow_description parameter is required")
	}

	if p.WorkflowDescription == "" {
		return "", fmt.Errorf("workflow_description cannot be empty")
	}

	if triggerType, ok := params["trigger_type"].(string); ok {
		p.TriggerType = strings.TrimSpace(strings.ToLower(triggerType))
	}

	if integrations, ok := params["integrations"].([]interface{}); ok {
		for _, integration := range integrations {
			if str, ok := integration.(string); ok {
				p.Integrations = append(p.Integrations, strings.TrimSpace(strings.ToLower(str)))
			}
		}
	}

	// Generate workflow
	workflow, err := generateWorkflow(p)
	if err != nil {
		return "", fmt.Errorf("failed to generate workflow: %v", err)
	}

	content := fmt.Sprintf("# Generated N8N Workflow\n\n**Description**: %s\n\n", p.WorkflowDescription)
	if p.TriggerType != "" {
		content += fmt.Sprintf("**Trigger Type**: %s\n", p.TriggerType)
	}
	if len(p.Integrations) > 0 {
		content += fmt.Sprintf("**Integrations**: %s\n", strings.Join(p.Integrations, ", "))
	}
	content += "\n## Workflow YAML\n\n```yaml\n" + workflow + "\n```\n\n"
	content += "## Usage Instructions\n\n"
	content += "1. Copy the YAML configuration above\n"
	content += "2. Save it to a `.yaml` file (e.g., `my-workflow.yaml`)\n"
	content += "3. Use the n8n-cli to deploy: `npx @edenreich/n8n-cli push my-workflow.yaml`\n"
	content += "4. Configure any required credentials in your n8n instance\n"
	content += "5. Test the workflow by triggering it according to your trigger type\n\n"
	content += "## Next Steps\n\n"
	content += "- Review and customize node parameters as needed\n"
	content += "- Add error handling nodes if required\n"
	content += "- Set up proper credentials for external services\n"
	content += "- Test the workflow in a development environment first\n"

	return content, nil
}

// generateWorkflow creates a complete N8N workflow based on parameters
func generateWorkflow(params GenerateN8nWorkflowParams) (string, error) {
	var builder strings.Builder

	// Generate workflow metadata
	builder.WriteString("# N8N Workflow Configuration\n")
	builder.WriteString("# Generated by n8n-agent\n\n")
	builder.WriteString("name: \"" + sanitizeWorkflowName(params.WorkflowDescription) + "\"\n")
	builder.WriteString("active: true\n\n")
	builder.WriteString("nodes:\n")

	nodeId := 1
	positions := [][]int{{100, 200}, {300, 200}, {500, 200}, {700, 200}, {900, 200}}

	// Generate trigger node
	triggerNode, triggerNodeId := generateTriggerNode(params.TriggerType, nodeId, positions[0])
	builder.WriteString(triggerNode)
	nodeId++

	// Generate integration nodes based on workflow description and integrations
	integrationNodes := generateIntegrationNodes(params, nodeId, positions[1:])
	builder.WriteString(integrationNodes)

	// Generate connections
	builder.WriteString("\nconnections:\n")
	builder.WriteString(fmt.Sprintf("  \"%s\":\n", triggerNodeId))
	builder.WriteString("    main:\n")
	builder.WriteString("      - - node: \"process-data\"\n")
	builder.WriteString("          type: main\n")
	builder.WriteString("          index: 0\n")

	return builder.String(), nil
}

// generateTriggerNode creates a trigger node based on the specified type
func generateTriggerNode(triggerType string, nodeId int, position []int) (string, string) {
	var builder strings.Builder
	var nodeName, nodeType string

	switch triggerType {
	case "webhook":
		nodeName = "webhook-trigger"
		nodeType = "n8n-nodes-base.webhook"
		builder.WriteString(fmt.Sprintf("  - id: \"%s\"\n", nodeName))
		builder.WriteString("    name: \"Webhook Trigger\"\n")
		builder.WriteString("    parameters:\n")
		builder.WriteString("      httpMethod: \"POST\"\n")
		builder.WriteString("      path: \"webhook\"\n")
		builder.WriteString("      responseMode: \"onReceived\"\n")

	case "schedule", "cron":
		nodeName = "schedule-trigger"
		nodeType = "n8n-nodes-base.scheduleTrigger"
		builder.WriteString(fmt.Sprintf("  - id: \"%s\"\n", nodeName))
		builder.WriteString("    name: \"Schedule Trigger\"\n")
		builder.WriteString("    parameters:\n")
		builder.WriteString("      rule:\n")
		builder.WriteString("        interval:\n")
		builder.WriteString("          - field: \"minutes\"\n")
		builder.WriteString("            minute: 30\n")

	case "manual":
		nodeName = "manual-trigger"
		nodeType = "n8n-nodes-base.manualTrigger"
		builder.WriteString(fmt.Sprintf("  - id: \"%s\"\n", nodeName))
		builder.WriteString("    name: \"Manual Trigger\"\n")
		builder.WriteString("    parameters: {}\n")

	default:
		// Default to manual trigger
		nodeName = "manual-trigger"
		nodeType = "n8n-nodes-base.manualTrigger"
		builder.WriteString(fmt.Sprintf("  - id: \"%s\"\n", nodeName))
		builder.WriteString("    name: \"Manual Trigger\"\n")
		builder.WriteString("    parameters: {}\n")
	}

	builder.WriteString(fmt.Sprintf("    position: [%d, %d]\n", position[0], position[1]))
	builder.WriteString(fmt.Sprintf("    type: \"%s\"\n\n", nodeType))

	return builder.String(), nodeName
}

// generateIntegrationNodes creates nodes based on integrations and workflow description
func generateIntegrationNodes(params GenerateN8nWorkflowParams, startNodeId int, positions [][]int) string {
	var builder strings.Builder
	posIndex := 0

	// Analyze workflow description for common patterns
	description := strings.ToLower(params.WorkflowDescription)

	// Add data processing node
	if posIndex < len(positions) {
		builder.WriteString("  - id: \"process-data\"\n")
		builder.WriteString("    name: \"Process Data\"\n")
		builder.WriteString("    parameters:\n")
		builder.WriteString("      jsCode: |\n")
		builder.WriteString("        // Process and transform the incoming data\n")
		builder.WriteString("        const processedData = {\n")
		builder.WriteString("          timestamp: new Date().toISOString(),\n")
		builder.WriteString("          originalData: $input.all(),\n")
		builder.WriteString("          processed: true\n")
		builder.WriteString("        };\n")
		builder.WriteString("        return [processedData];\n")
		builder.WriteString(fmt.Sprintf("    position: [%d, %d]\n", positions[posIndex][0], positions[posIndex][1]))
		builder.WriteString("    type: \"n8n-nodes-base.code\"\n\n")
		posIndex++
	}

	// Add integration-specific nodes
	for _, integration := range params.Integrations {
		if posIndex >= len(positions) {
			break
		}

		switch integration {
		case "slack":
			builder.WriteString(generateSlackNode(positions[posIndex]))
		case "gmail", "email":
			builder.WriteString(generateEmailNode(positions[posIndex]))
		case "database", "mysql", "postgres":
			builder.WriteString(generateDatabaseNode(positions[posIndex]))
		case "http", "api":
			builder.WriteString(generateHttpNode(positions[posIndex]))
		case "webhook":
			builder.WriteString(generateWebhookResponseNode(positions[posIndex]))
		}
		posIndex++
	}

	// Add nodes based on workflow description patterns
	if (strings.Contains(description, "notification") || strings.Contains(description, "alert")) && posIndex < len(positions) {
		if !contains(params.Integrations, "slack") {
			builder.WriteString(generateSlackNode(positions[posIndex]))
			posIndex++
		}
	}

	if (strings.Contains(description, "email") || strings.Contains(description, "send")) && posIndex < len(positions) {
		if !contains(params.Integrations, "gmail") && !contains(params.Integrations, "email") {
			builder.WriteString(generateEmailNode(positions[posIndex]))
			posIndex++
		}
	}

	if (strings.Contains(description, "store") || strings.Contains(description, "save")) && posIndex < len(positions) {
		if !contains(params.Integrations, "database") {
			builder.WriteString(generateDatabaseNode(positions[posIndex]))
			posIndex++
		}
	}

	return builder.String()
}

// Node generation helper functions
func generateSlackNode(position []int) string {
	return fmt.Sprintf(`  - id: "slack-notification"
    name: "Slack Notification"
    parameters:
      resource: "message"
      operation: "post"
      channel: "#general"
      text: "Workflow executed successfully: {{ $json.timestamp }}"
      username: "n8n-bot"
    position: [%d, %d]
    type: "n8n-nodes-base.slack"

`, position[0], position[1])
}

func generateEmailNode(position []int) string {
	return fmt.Sprintf(`  - id: "email-notification"
    name: "Email Notification"
    parameters:
      fromEmail: "noreply@company.com"
      toEmail: "admin@company.com"
      subject: "N8N Workflow Notification"
      text: "The workflow has been executed successfully."
      html: "<h1>Workflow Complete</h1><p>The workflow executed at {{ $json.timestamp }}</p>"
    position: [%d, %d]
    type: "n8n-nodes-base.emailSend"

`, position[0], position[1])
}

func generateDatabaseNode(position []int) string {
	return fmt.Sprintf(`  - id: "database-insert"
    name: "Database Insert"
    parameters:
      operation: "insert"
      table: "workflow_logs"
      columns: "timestamp,data,status"
      additionalFields:
        mode: "defineBelow"
        values:
          timestamp: "={{ $json.timestamp }}"
          data: "={{ JSON.stringify($json.originalData) }}"
          status: "completed"
    position: [%d, %d]
    type: "n8n-nodes-base.postgres"

`, position[0], position[1])
}

func generateHttpNode(position []int) string {
	return fmt.Sprintf(`  - id: "http-request"
    name: "HTTP Request"
    parameters:
      method: "POST"
      url: "https://api.example.com/webhook"
      sendBody: true
      contentType: "json"
      jsonParameters: true
      body:
        timestamp: "={{ $json.timestamp }}"
        data: "={{ $json.originalData }}"
    position: [%d, %d]
    type: "n8n-nodes-base.httpRequest"

`, position[0], position[1])
}

func generateWebhookResponseNode(position []int) string {
	return fmt.Sprintf(`  - id: "webhook-response"
    name: "Webhook Response"
    parameters:
      respondWith: "json"
      responseBody: |
        {
          "status": "success",
          "message": "Workflow completed successfully",
          "timestamp": "{{ $json.timestamp }}"
        }
    position: [%d, %d]
    type: "n8n-nodes-base.respondToWebhook"

`, position[0], position[1])
}

// Helper functions
func sanitizeWorkflowName(description string) string {
	// Convert description to a valid workflow name
	name := strings.TrimSpace(description)
	if len(name) > 50 {
		name = name[:47] + "..."
	}
	// Replace invalid characters
	name = strings.ReplaceAll(name, "\"", "'")
	return name
}

func contains(slice []string, item string) bool {
	for _, s := range slice {
		if s == item {
			return true
		}
	}
	return false
}