version = 1

[install]
go.pkg-path = "go"
go.version = "^1.24"

golangci-lint.pkg-path = "golangci-lint"
golangci-lint.version = "^2.4.0"
golangci-lint.pkg-group = "common"

deno.pkg-path = "deno"
deno.version = "^2.4.4"
deno.pkg-group = "common"

go-task.pkg-path = "go-task"
go-task.pkg-group = "common"

git.pkg-path = "git"
git.pkg-group = "common"

docker.pkg-path = "docker"
docker.pkg-group = "common"

claude-code.pkg-path = "claude-code"
claude-code.pkg-group = "common"

# Note: ADL CLI is required for `task generate` but not available in standard package repositories
# Manual installation may be required - see CLAUDE.md for installation instructions

[hook]
on-activate = '''
  echo "🌟 Welcome to n8n-agent development environment!"
  echo "Go version: $(go version)"
'''
