// Code generated by ADL CLI v0.39.1. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package tools

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	zap "go.uber.org/zap"
)

// newTestReadTool builds a Read tool with the supplied config, bypassing
// envconfig so each test pins the exact behavior under test.
func newTestReadTool(cfg ReadConfig) *ReadTool {
	return &ReadTool{logger: zap.NewNop(), cfg: cfg}
}

func TestReadTool_DisabledReturnsError(t *testing.T) {
	t.Parallel()
	tool := newTestReadTool(ReadConfig{Enabled: false, MaxLines: 100})
	if _, err := tool.Handler(context.Background(), map[string]any{"file_path": "anything"}); err == nil {
		t.Fatalf("expected error when tool is disabled, got nil")
	}
}

func TestReadTool_RequiresFilePath(t *testing.T) {
	t.Parallel()
	tool := newTestReadTool(ReadConfig{Enabled: true, MaxLines: 100})
	if _, err := tool.Handler(context.Background(), map[string]any{}); err == nil {
		t.Fatalf("expected error when file_path is missing, got nil")
	}
}

func TestReadTool_ReadsFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "hello.txt")
	if err := os.WriteFile(path, []byte("hello\nworld\n"), 0o644); err != nil {
		t.Fatalf("seed file: %v", err)
	}

	tool := newTestReadTool(ReadConfig{Enabled: true, MaxLines: 100})
	out, err := tool.Handler(context.Background(), map[string]any{"file_path": path})
	if err != nil {
		t.Fatalf("Handler returned error: %v", err)
	}

	var payload map[string]any
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}
	if got := payload["content"].(string); !strings.Contains(got, "hello") || !strings.Contains(got, "world") {
		t.Fatalf("expected file content in response, got %q", got)
	}
	if got := int(payload["lines_read"].(float64)); got != 2 {
		t.Fatalf("expected lines_read=2, got %d", got)
	}
}

func TestReadTool_HonorsOffsetAndLimit(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	path := filepath.Join(dir, "lines.txt")
	if err := os.WriteFile(path, []byte("a\nb\nc\nd\ne\n"), 0o644); err != nil {
		t.Fatalf("seed file: %v", err)
	}

	tool := newTestReadTool(ReadConfig{Enabled: true, MaxLines: 100})
	out, err := tool.Handler(context.Background(), map[string]any{
		"file_path": path,
		"offset":    2,
		"limit":     2,
	})
	if err != nil {
		t.Fatalf("Handler returned error: %v", err)
	}

	var payload map[string]any
	if err := json.Unmarshal([]byte(out), &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}
	got := payload["content"].(string)
	want := "b\nc\n"
	if got != want {
		t.Fatalf("expected slice %q, got %q", want, got)
	}
}

func TestReadTool_RejectsImageExtensions(t *testing.T) {
	t.Parallel()
	tool := newTestReadTool(ReadConfig{Enabled: true, MaxLines: 100})
	if _, err := tool.Handler(context.Background(), map[string]any{"file_path": "screenshot.PNG"}); err == nil {
		t.Fatalf("expected error for image extension, got nil")
	}
}

func TestReadTool_EnforcesAllowedRoots(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	allowed := filepath.Join(dir, "allowed")
	if err := os.MkdirAll(allowed, 0o755); err != nil {
		t.Fatalf("mkdir allowed: %v", err)
	}
	insidePath := filepath.Join(allowed, "ok.txt")
	if err := os.WriteFile(insidePath, []byte("ok\n"), 0o644); err != nil {
		t.Fatalf("seed inside file: %v", err)
	}
	outsidePath := filepath.Join(dir, "outside.txt")
	if err := os.WriteFile(outsidePath, []byte("nope\n"), 0o644); err != nil {
		t.Fatalf("seed outside file: %v", err)
	}

	tool := newTestReadTool(ReadConfig{Enabled: true, MaxLines: 100, AllowedRoots: []string{allowed}})

	if _, err := tool.Handler(context.Background(), map[string]any{"file_path": insidePath}); err != nil {
		t.Fatalf("expected file inside allowed root to succeed, got: %v", err)
	}
	if _, err := tool.Handler(context.Background(), map[string]any{"file_path": outsidePath}); err == nil {
		t.Fatalf("expected file outside allowed root to be rejected, got nil")
	}
}
