// Code generated by ADL CLI v0.52.0. DO NOT EDIT.
// This file was automatically generated from an ADL (Agent Definition Language) specification.
// Manual changes to this file may be overwritten during regeneration.

package tools

import (
	"context"
	"crypto/rand"
	"encoding/hex"

	envconfig "github.com/sethvargo/go-envconfig"
	otel "go.opentelemetry.io/otel"
	attribute "go.opentelemetry.io/otel/attribute"
	baggage "go.opentelemetry.io/otel/baggage"
	trace "go.opentelemetry.io/otel/trace"

	config "github.com/inference-gateway/adk/server/config"
)

// tracerName is the instrumentation scope reported for the spans the
// generated built-in tools emit. Matching the module path makes the spans
// easy to filter by library in a tracing backend.
const tracerName = "github.com/inference-gateway/n8n-agent/tools"

// telemetrySettings mirrors how the generated config wraps the ADK telemetry
// config (the A2A_ prefix), so the tool spans resolve the same attribute and
// baggage keys as the ADK's request middleware. Reading them from the ADK's own
// config keeps the tool span correlated with the a2a.request span even when the
// keys are overridden.
type telemetrySettings struct {
	Telemetry config.TelemetryConfig `env:",prefix=A2A_TELEMETRY_"`
}

// sessionIDKey and toolCallIDKey are the span-attribute / baggage-member keys,
// resolved once from the environment. They honor
// A2A_TELEMETRY_ATTR_SESSION_ID_KEY / A2A_TELEMETRY_ATTR_TOOL_CALL_ID_KEY and
// otherwise fall back to the OTel semantic-convention defaults (session.id /
// gen_ai.tool.call.id) exactly as the ADK does.
var sessionIDKey, toolCallIDKey = resolveAttrKeys()

func resolveAttrKeys() (string, string) {
	var s telemetrySettings
	if err := envconfig.Process(context.Background(), &s); err != nil {
		return config.DefaultAttrSessionIDKey, config.DefaultAttrToolCallIDKey
	}
	return s.Telemetry.SessionIDKey(), s.Telemetry.ToolCallIDKey()
}

// startToolSpan opens a span around a built-in tool call so per-tool-call
// latency is captured. It ensures a tool-call id is present (minting one when
// the caller did not propagate it) and carries the session id from the inbound
// baggage, exposing both as span attributes so the tool span correlates with the
// ADK's a2a.request span in the tracing backend. The attribute and baggage keys
// follow the OTel semantic conventions (session.id / gen_ai.tool.call.id) and
// stay in sync with the ADK via A2A_TELEMETRY_ATTR_* overrides.
//
// Telemetry is a no-op unless A2A_TELEMETRY_ENABLE=true and a traces exporter is
// configured (A2A_OTEL_TRACES_EXPORTER=otlp); the ADK installs the global tracer
// provider only then. When export is off the tracer is a no-op, so this is always
// safe to call. Pair it with `defer span.End()` at the top of a tool Handler.
func startToolSpan(ctx context.Context, toolName string) trace.Span {
	_, span := otel.Tracer(tracerName).Start(ctx, "tool."+toolName)
	if !span.IsRecording() {
		return span
	}

	bag := baggage.FromContext(ctx)

	callID := bag.Member(toolCallIDKey).Value()
	if callID == "" {
		callID = newToolCallID()
	}

	attrs := []attribute.KeyValue{attribute.String(toolCallIDKey, callID)}
	if sessionID := bag.Member(sessionIDKey).Value(); sessionID != "" {
		attrs = append(attrs, attribute.String(sessionIDKey, sessionID))
	}
	span.SetAttributes(attrs...)

	return span
}

// newToolCallID mints a random 128-bit identifier for a tool call when the
// caller did not propagate one via the tool-call-id baggage member.
func newToolCallID() string {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ""
	}
	return hex.EncodeToString(b[:])
}
